services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - air_tmp:/app/tmp
    depends_on:
      - db
    env_file: ".env"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  air_tmp:

