basePath: /v1
definitions:
  types.CreateAccountRequest:
    properties:
      first_name:
        maxLength: 100
        minLength: 3
        type: string
      last_name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        minLength: 8
        type: string
    required:
    - first_name
    - last_name
    - password
    type: object
  types.LoginRequest:
    properties:
      number:
        type: integer
      password:
        type: string
    type: object
  types.TransferRequest:
    properties:
      amount:
        type: number
      to_account:
        type: integer
    required:
    - amount
    - to_account
    type: object
  types.UpdateAccountRequest:
    properties:
      balance:
        type: integer
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    required:
    - id
    type: object
host: localhost:3000
info:
  contact:
    email: None
    name: API Support
    url: None
  description: An API for a simple bank
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: None
  title: GoBank API
  version: "1.0"
paths:
  /account:
    get:
      description: Get all accounts
      responses:
        "200":
          description: OK
      summary: Account
      tags:
      - account
    post:
      description: Create an account
      parameters:
      - description: Create Account Data
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/types.CreateAccountRequest'
      responses:
        "200":
          description: OK
      summary: Account
      tags:
      - account
    put:
      description: Update an account
      parameters:
      - description: Update Account Data
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/types.UpdateAccountRequest'
      responses:
        "200":
          description: OK
      summary: Account
      tags:
      - account
  /account/{id}:
    delete:
      description: Delete an account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Account
      tags:
      - account
    get:
      description: Get account by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Account
      tags:
      - account
  /health:
    get:
      description: Check if the server is up and running
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - health
  /login:
    post:
      consumes:
      - application/json
      description: Login to the API
      parameters:
      - description: Login data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      responses:
        "200":
          description: OK
      summary: Login
      tags:
      - auth
  /transfer:
    post:
      consumes:
      - application/json
      description: Transfer money between accounts
      parameters:
      - description: Transfer Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.TransferRequest'
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Transfer
      tags:
      - transfer
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
